### ISSUE TITLE
No matching routes for OPTIONS /api/0/buckets/aw-watcher-web-firefox/heartbeat?pulsetime=80.

### ISSUE THREAD

**Issue by Alwinator** [ActivityWatch/aw-watcher-web#68]
```
2021-05-10 13:17:59 [INFO ]: Searching for bundled modules in: ['/home/alwin/apps/activitywatch/aw_qt', '/home/alwin/apps/activitywatch']  (aw_qt.manager:67)
2021-05-10 13:17:59 [WARNING]: Found matching file but was not executable: /home/alwin/apps/activitywatch/aw-qt.desktop  (aw_qt.manager:55)
2021-05-10 13:17:59 [WARNING]: Found matching file but was not executable: /home/alwin/apps/activitywatch/aw-server-rust/aw-server.service  (aw_qt.manager:55)
2021-05-10 13:17:59 [INFO ]: Found bundled modules:  (aw_qt.manager:72)
2021-05-10 13:17:59 [INFO ]:  - aw-qt at /home/alwin/apps/activitywatch/aw-qt  (aw_qt.manager:24)
2021-05-10 13:17:59 [INFO ]:  - aw-server at /home/alwin/apps/activitywatch/aw-server/aw-server  (aw_qt.manager:24)
2021-05-10 13:17:59 [INFO ]:  - aw-watcher-afk at /home/alwin/apps/activitywatch/aw-watcher-afk/aw-watcher-afk  (aw_qt.manager:24)
2021-05-10 13:17:59 [INFO ]:  - aw-server-rust at /home/alwin/apps/activitywatch/aw-server-rust/aw-server-rust  (aw_qt.manager:24)
2021-05-10 13:17:59 [INFO ]:  - aw-table-watcher at /home/alwin/apps/activitywatch/aw-table-watcher/aw-table-watcher  (aw_qt.manager:24)
2021-05-10 13:17:59 [INFO ]:  - aw-watcher-window at /home/alwin/apps/activitywatch/aw-watcher-window/aw-watcher-window  (aw_qt.manager:24)
2021-05-10 13:17:59 [INFO ]: Found system modules:  (aw_qt.manager:99)
2021-05-10 13:17:59 [INFO ]: Starting module aw-server-rust  (aw_qt.manager:128)
2021-05-10 13:17:59 [INFO ]: Starting module aw-watcher-window  (aw_qt.manager:128)
2021-05-10 13:17:59 [INFO ]: Starting module aw-table-watcher  (aw_qt.manager:128)
[2021-05-10 13:17:59][INFO][aw_server]: Using DB at path "/home/alwin/.local/share/activitywatch/aw-server-rust/sqlite.db"
[2021-05-10 13:17:59][INFO][aw_server]: Using aw-webui assets at path "/home/alwin/apps/activitywatch/aw-server-rust/./static/"
[2021-05-10 13:17:59][INFO][aw_server::endpoints]: Starting aw-server-rust at 127.0.0.1:5600
[2021-05-10 13:17:59][INFO][launch]: 🔧 Configured for development.
2021-05-10 13:17:59 [INFO ]: Starting module aw-watcher-afk  (aw_qt.manager:128)
[2021-05-10 13:17:59][INFO][launch]: 🚀 Rocket has launched from http://127.0.0.1:5600
2021-05-10 13:17:59 [INFO ]: Creating trayicon...  (aw_qt.trayicon:200)
/usr/lib/x86_64-linux-gnu/gvfs/libgvfscommon.so: undefined symbol: g_task_set_name
Failed to load module: /usr/lib/x86_64-linux-gnu/gio/modules/libgvfsdbus.so

(aw-qt:28291): Gtk-WARNING **: Theme parsing error: gtk.css:6129:18: Missing name of pseudo-class

(aw-qt:28291): Gtk-WARNING **: Theme parsing error: gtk.css:6134:20: Missing name of pseudo-class

(aw-qt:28291): Gtk-WARNING **: Theme parsing error: gtk.css:6151:17: Missing name of pseudo-class

(aw-qt:28291): Gtk-WARNING **: Theme parsing error: gtk.css:6166:18: '-gtk-icon-effect' is not a valid property name

(aw-qt:28291): Gtk-WARNING **: Theme parsing error: gtk.css:6179:16: Missing name of pseudo-class

(aw-qt:28291): Gtk-WARNING **: Theme parsing error: gtk.css:6184:16: Missing name of pseudo-class

(aw-qt:28291): Gtk-WARNING **: Theme parsing error: gtk.css:6200:15: Missing name of pseudo-class
2021-05-10 13:17:59 [INFO ]: Initialized aw-qt and trayicon succesfully  (aw_qt.trayicon:235)
2021-05-10 13:17:59 [INFO ]: aw-watcher-table started  (aw_watcher_table.watcher:25)
2021-05-10 13:17:59 [INFO ]: aw-watcher-window started  (aw_watcher_window.main:44)
2021-05-10 13:17:59 [INFO ]: aw-watcher-afk started  (aw_watcher_afk.afk:53)
[2021-05-10 13:18:00][ERROR][hyper::http::h1]: Cannot include a body with this kind of message
[2021-05-10 13:18:00][ERROR][_]: Failed to write response: Custom { kind: WriteZero, error: "failed to write whole buffer" }.
2021-05-10 13:18:00 [INFO ]: Connection to aw-server established by aw-watcher-table  (aw_client.client:405)
[2021-05-10 13:18:00][ERROR][hyper::http::h1]: Cannot include a body with this kind of message
[2021-05-10 13:18:00][ERROR][_]: Failed to write response: Custom { kind: WriteZero, error: "failed to write whole buffer" }.
2021-05-10 13:18:00 [INFO ]: Connection to aw-server established by aw-watcher-window  (aw_client.client:348)
[2021-05-10 13:18:00][ERROR][hyper::http::h1]: Cannot include a body with this kind of message
[2021-05-10 13:18:00][ERROR][_]: Failed to write response: Custom { kind: WriteZero, error: "failed to write whole buffer" }.
2021-05-10 13:18:00 [INFO ]: Connection to aw-server established by aw-watcher-afk  (aw_client.client:348)
2021-05-10 13:19:36 [WARNING]: Unable to get window class, got a BadWindow exception.  (aw_watcher_window.xlib:85)

2021-05-10 13:19:36 [WARNING]: Code made an unclear branch  (aw_watcher_window.xlib:91)
2021-05-10 13:19:36 [WARNING]: Unable to get window query_tree().parent, got a BadWindow exception from Xlib  (aw_watcher_window.xlib:95)
2021-05-10 13:19:36 [WARNING]: Unable to get window property NET_WM_NAME, got a BadWindow exception from Xlib  (aw_watcher_window.xlib:54)
2021-05-10 13:19:36 [ERROR]: Exception thrown while trying to get active window: <class 'Xlib.error.BadWindow'>: code = 3, resource_id = <class 'Xlib.xobject.resource.Resource'>(0x04814cc8), sequence_number = 392, major_opcode = 20, minor_opcode = 0  (aw_watcher_window.main:71)
Traceback (most recent call last):
  File "aw_watcher_window/main.py", line 68, in heartbeat_loop
  File "aw_watcher_window/lib.py", line 44, in get_current_window
  File "aw_watcher_window/lib.py", line 14, in get_current_window_linux
  File "aw_watcher_window/xlib.py", line 60, in get_window_name
  File "site-packages/Xlib/xobject/drawable.py", line 669, in get_wm_name
  File "site-packages/Xlib/xobject/drawable.py", line 487, in get_full_text_property
  File "site-packages/Xlib/xobject/drawable.py", line 472, in get_full_property
  File "site-packages/Xlib/xobject/drawable.py", line 461, in get_property
  File "site-packages/Xlib/protocol/rq.py", line 1369, in __init__
  File "site-packages/Xlib/protocol/rq.py", line 1389, in reply
Xlib.error.BadWindow: <class 'Xlib.error.BadWindow'>: code = 3, resource_id = <class 'Xlib.xobject.resource.Resource'>(0x04814cc8), sequence_number = 392, major_opcode = 20, minor_opcode = 0
Opening dashboard
[2021-05-10 13:19:39][WARN][_]: Response was `None`.
[2021-05-10 13:19:39][WARN][_]: Responding with 404 Not Found catcher.
[2021-05-10 13:19:39][WARN][_]: Response was `None`.
[2021-05-10 13:19:39][WARN][_]: Responding with 404 Not Found catcher.
[2021-05-10 13:19:39][WARN][_]: Response was `None`.
[2021-05-10 13:19:39][WARN][_]: Response was `None`.
[2021-05-10 13:19:39][WARN][_]: Responding with 404 Not Found catcher.
[2021-05-10 13:19:39][WARN][_]: Responding with 404 Not Found catcher.
[2021-05-10 13:21:03][INFO][aw_datastore::datastore]: Created bucket aw-watcher-Python_monster
[2021-05-10 13:21:05][ERROR][_]: Couldn't parse JSON body: Error("invalid type: map, expected a sequence", line: 1, column: 0)
[2021-05-10 13:21:05][WARN][_]: Responding with 422 Unprocessable Entity catcher.
[2021-05-10 13:22:08][ERROR][_]: No matching routes for OPTIONS /api/0/buckets/aw-watcher-web-firefox.
[2021-05-10 13:22:08][WARN][_]: Responding with 404 Not Found catcher.
[2021-05-10 13:22:08][INFO][aw_datastore::datastore]: Created bucket aw-watcher-web-firefox
[2021-05-10 13:22:13][ERROR][_]: No matching routes for OPTIONS /api/0/buckets/aw-watcher-web-firefox/heartbeat?pulsetime=80.
[2021-05-10 13:22:13][WARN][_]: Responding with 404 Not Found catcher.
[2021-05-10 13:22:33][ERROR][_]: No matching routes for OPTIONS /api/0/buckets/aw-watcher-web-firefox/heartbeat?pulsetime=80.
[2021-05-10 13:22:33][WARN][_]: Responding with 404 Not Found catcher.
[2021-05-10 13:22:38][ERROR][_]: No matching routes for OPTIONS /api/0/buckets/aw-watcher-web-firefox/heartbeat?pulsetime=80.
[2021-05-10 13:22:38][WARN][_]: Responding with 404 Not Found catcher.
[2021-05-10 13:22:58][ERROR][_]: No matching routes for OPTIONS /api/0/buckets/aw-watcher-web-firefox/heartbeat?pulsetime=80.
[2021-05-10 13:22:58][WARN][_]: Responding with 404 Not Found catcher.
[2021-05-10 13:23:03][ERROR][_]: No matching routes for OPTIONS /api/0/buckets/aw-watcher-web-firefox/heartbeat?pulsetime=80.
[2021-05-10 13:23:03][WARN][_]: Responding with 404 Not Found catcher.
[2021-05-10 13:23:16][ERROR][_]: Couldn't parse JSON body: Error("invalid type: map, expected a sequence", line: 1, column: 0)
[2021-05-10 13:23:16][ERROR][_]: Couldn't parse JSON body: Error("invalid type: map, expected a sequence", line: 1, column: 0)
[2021-05-10 13:23:16][WARN][_]: Responding with 422 Unprocessable Entity catcher.
[2021-05-10 13:23:16][WARN][_]: Responding with 422 Unprocessable Entity catcher.
[2021-05-10 13:23:16][ERROR][_]: Couldn't parse JSON body: Error("invalid type: map, expected a sequence", line: 1, column: 0)
[2021-05-10 13:23:16][WARN][_]: Responding with 422 Unprocessable Entity catcher.
[2021-05-10 13:23:16][ERROR][_]: Couldn't parse JSON body: Error("invalid type: map, expected a sequence", line: 1, column: 0)
[2021-05-10 13:23:16][WARN][_]: Responding with 422 Unprocessable Entity catcher.
[2021-05-10 13:23:16][ERROR][_]: Couldn't parse JSON body: Error("invalid type: map, expected a sequence", line: 1, column: 0)
[2021-05-10 13:23:16][WARN][_]: Responding with 422 Unprocessable Entity catcher.
[2021-05-10 13:23:16][ERROR][_]: Couldn't parse JSON body: Error("invalid type: map, expected a sequence", line: 1, column: 0)
[2021-05-10 13:23:16][WARN][_]: Responding with 422 Unprocessable Entity catcher.
[2021-05-10 13:23:16][ERROR][_]: Couldn't parse JSON body: Error("invalid type: map, expected a sequence", line: 1, column: 0)
[2021-05-10 13:23:16][WARN][_]: Responding with 422 Unprocessable Entity catcher.
[2021-05-10 13:23:28][ERROR][_]: No matching routes for OPTIONS /api/0/buckets/aw-watcher-web-firefox/heartbeat?pulsetime=80.
[2021-05-10 13:23:28][WARN][_]: Responding with 404 Not Found catcher.
[2021-05-10 13:23:48][ERROR][_]: No matching routes for OPTIONS /api/0/buckets/aw-watcher-web-firefox/heartbeat?pulsetime=80.
[2021-05-10 13:23:48][WARN][_]: Responding with 404 Not Found catcher.
alwin@monster ~/.c/a/aw-watcher-table> [2021-05-10 13:24:08][ERROR][_]: No matching routes for OPTIONS /api/0/buckets/aw-watcher-web-firefox/heartbeat?pulsetime=80.
[2021-05-10 13:24:08][WARN][_]: Responding with 404 Not Found catcher.
[2021-05-10 13:24:28][ERROR][_]: No matching routes for OPTIONS /api/0/buckets/aw-watcher-web-firefox/heartbeat?pulsetime=80.
[2021-05-10 13:24:28][WARN][_]: Responding with 404 Not Found catcher.
[2021-05-10 13:24:48][ERROR][_]: No matching routes for OPTIONS /api/0/buckets/aw-watcher-web-firefox/heartbeat?pulsetime=80.
[2021-05-10 13:24:48][WARN][_]: Responding with 404 Not Found catcher.
[2021-05-10 13:24:58][ERROR][_]: No matching routes for OPTIONS /api/0/buckets/aw-watcher-web-firefox/heartbeat?pulsetime=80.
[2021-05-10 13:24:58][WARN][_]: Responding with 404 Not Found catcher.
[2021-05-10 13:25:18][ERROR][_]: No matching routes for OPTIONS /api/0/buckets/aw-watcher-web-firefox/heartbeat?pulsetime=80.
[2021-05-10 13:25:18][WARN][_]: Responding with 404 Not Found catcher.
[2021-05-10 13:25:33][ERROR][_]: No matching routes for OPTIONS /api/0/buckets/aw-watcher-web-firefox/heartbeat?pulsetime=80.
[2021-05-10 13:25:33][WARN][_]: Responding with 404 Not Found catcher.
[2021-05-10 13:25:38][ERROR][_]: No matching routes for OPTIONS /api/0/buckets/aw-watcher-web-firefox/heartbeat?pulsetime=80.
[2021-05-10 13:25:38][WARN][_]: Responding with 404 Not Found catcher.
[2021-05-10 13:25:58][ERROR][_]: No matching routes for OPTIONS /api/0/buckets/aw-watcher-web-firefox/heartbeat?pulsetime=80.
[2021-05-10 13:25:58][WARN][_]: Responding with 404 Not Found catcher.

```

**Comment by Alwinator** [comment]
I just found this Issue, I think my one is a dublicate:
https://github.com/ActivityWatch/aw-server-rust/issues/42

**Comment by ErikBjare** [comment]
Just to be clear, does this impact the functioning in any way?

Skimmed the other lines and saw this too:

```
[2021-05-10 13:21:05][ERROR][_]: Couldn't parse JSON body: Error("invalid type: map, expected a sequence", line: 1, column: 0)
[2021-05-10 13:21:05][WARN][_]: Responding with 422 Unprocessable Entity catcher.
```

Not sure what the cause is there...
